# CryoProtect v2 - Prometheus Configuration

global:
  scrape_interval: 15s  # How frequently to scrape targets
  evaluation_interval: 15s  # How frequently to evaluate rules
  scrape_timeout: 10s  # How long until a scrape request times out

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "rules/api_alerts.yml"
  - "rules/system_alerts.yml"

# Scrape configurations
scrape_configs:
  # CryoProtect API metrics
  - job_name: 'cryoprotect-api'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:5000']
        labels:
          service: 'cryoprotect-api'
          environment: 'production'

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9100']
        labels:
          service: 'node-exporter'
          environment: 'production'

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'
          environment: 'production'

  # Grafana metrics
  - job_name: 'grafana'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:3000']
        labels:
          service: 'grafana'
          environment: 'production'